services:
  fso-server:
    build: .
    image: fso-server:latest
    container_name: fso-server
    ports:
      - "9000:9000"
      - "33100:33100"
      - "34100:34100"
      - "35100:35100"
    depends_on:
      - fso-db
    environment:
      DB_HOST: fso-db
      DB_PORT: 3306
      DB_USER: fsoserver
      DB_PASSWORD: fsopass
      DB_NAME: fso
      GAME_LOCATION: ./game
      SIM_NFS: ./nfs
    volumes:
      - "${GAME_PATH}:/app/src/game"
      - "${NFS_PATH}:/app/src/nfs"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "fso-db", "-u", "fsoserver", "-pfsopass"]
      interval: 5s
      retries: 20
      start_period: 10s
      timeout: 5s

  fso-db:
    image: mariadb:10.5
    container_name: fso-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fso
      MYSQL_USER: fsoserver
      MYSQL_PASSWORD: fsopass
    ports:
      - "3306:3306"
    volumes:
      - fso-db-data:/var/lib/mysql

volumes:
  fso-db-data:
